In [1]:
from tensorflow import keras
from keras.layers import Dense, SimpleRNN, Dropout, Input, Flatten, LSTM, Embedding, Bidirectional
import numpy as np
import pandas as pd
import ast
import re

In [2]:
#import gensim.downloader as api
#model_embedding = api.load('glove-twitter-100')

In [3]:
def crypto(message, sdvig):
    message_crypto = ""
    for i in message:
        message_crypto += chr(ord(i)+sdvig)
    return message_crypto

In [4]:
crypto("RNN IS NOT AI", 2)

'TPP"KU"PQV"CK'

In [5]:
def message_to_numbers(message):
    message_numbers = []
    for i in message:
        message_numbers.append(ord(i))
    return np.array(message_numbers)

In [6]:
message_to_numbers('ABC'), message_to_numbers(crypto('ABC', 2))

(array([65, 66, 67]), array([67, 68, 69]))

In [7]:
X = np.array([[]])
y = np.array([[]])

In [8]:
X = np.append(X, message_to_numbers(crypto('ABCDEFABCD', 2)))
X = np.append(X, message_to_numbers('ABCDEFABCD'))
X = np.append(X, message_to_numbers(crypto('GHTYUIUYTR', 3)))
X = np.append(X, message_to_numbers('GHTYUIUYTR'))
X = np.append(X, message_to_numbers(crypto('ABCDEFHJKL', 50)))
X = np.append(X, message_to_numbers('ABCDEFHJKL'))
X = np.append(X, message_to_numbers(crypto('GHTYUIUYTR', 15)))
X = np.append(X, message_to_numbers('GHTYUIUYTR'))
X = np.append(X, message_to_numbers(crypto('ABCDEFHJKL', 64)))
X = np.append(X, message_to_numbers('ABCDEFHJKL'))
X=X.reshape(5, 2 * 10)
X

array([[ 67.,  68.,  69.,  70.,  71.,  72.,  67.,  68.,  69.,  70.,  65.,
         66.,  67.,  68.,  69.,  70.,  65.,  66.,  67.,  68.],
       [ 74.,  75.,  87.,  92.,  88.,  76.,  88.,  92.,  87.,  85.,  71.,
         72.,  84.,  89.,  85.,  73.,  85.,  89.,  84.,  82.],
       [115., 116., 117., 118., 119., 120., 122., 124., 125., 126.,  65.,
         66.,  67.,  68.,  69.,  70.,  72.,  74.,  75.,  76.],
       [ 86.,  87.,  99., 104., 100.,  88., 100., 104.,  99.,  97.,  71.,
         72.,  84.,  89.,  85.,  73.,  85.,  89.,  84.,  82.],
       [129., 130., 131., 132., 133., 134., 136., 138., 139., 140.,  65.,
         66.,  67.,  68.,  69.,  70.,  72.,  74.,  75.,  76.]])

In [9]:
y = np.array([2, 3, 50, 15, 64]).reshape(5, 1)
y

array([[ 2],
       [ 3],
       [50],
       [15],
       [64]])

In [10]:
model_rnn = keras.Sequential()



#model_rnn.add(LSTM(20, activation='linear', return_sequences=True))

model_rnn.add(Dense(1, activation='linear'))

model_rnn.compile(loss='mse', optimizer=keras.optimizers.Adam(0.1))

In [11]:
model_rnn.fit(X, y, epochs=10000)

Выходные данные были обрезаны до нескольких последних строк (5000).
1/1 [==============================] - 0s 7ms/step - loss: 9.2469e-07
Epoch 7502/10000
1/1 [==============================] - 0s 6ms/step - loss: 9.0761e-07
Epoch 7503/10000
1/1 [==============================] - 0s 8ms/step - loss: 9.0354e-07
Epoch 7504/10000
1/1 [==============================] - 0s 13ms/step - loss: 8.9352e-07
Epoch 7505/10000
1/1 [==============================] - 0s 7ms/step - loss: 9.0133e-07
Epoch 7506/10000
1/1 [==============================] - 0s 6ms/step - loss: 9.1702e-07
Epoch 7507/10000
1/1 [==============================] - 0s 5ms/step - loss: 9.2276e-07
Epoch 7508/10000
1/1 [==============================] - 0s 9ms/step - loss: 9.2932e-07
Epoch 7509/10000
1/1 [==============================] - 0s 6ms/step - loss: 9.3699e-07
Epoch 7510/10000
1/1 [==============================] - 0s 9ms/step - loss: 9.3209e-07
Epoch 7511/10000
1/1 [==============================] - 0s 6ms/step - loss: 9.

In [12]:
X_test = np.array([[]])

In [13]:
X_test = np.append(X_test, message_to_numbers(crypto('ABCDEFABCD', 2)))
X_test = np.append(X_test, message_to_numbers('ABCDEFABCD'))
X_test = np.append(X_test, message_to_numbers(crypto('GHTYUIUYTR', 7)))
X_test = np.append(X_test, message_to_numbers('GHTYUIUYTR'))
X_test = np.append(X_test, message_to_numbers(crypto('ABCDEFHJKL', 11)))
X_test = np.append(X_test, message_to_numbers('ABCDEFHJKL'))
X_test=X_test.reshape(3, 2 * 10)
X_test

array([[67., 68., 69., 70., 71., 72., 67., 68., 69., 70., 65., 66., 67.,
        68., 69., 70., 65., 66., 67., 68.],
       [78., 79., 91., 96., 92., 80., 92., 96., 91., 89., 71., 72., 84.,
        89., 85., 73., 85., 89., 84., 82.],
       [76., 77., 78., 79., 80., 81., 83., 85., 86., 87., 65., 66., 67.,
        68., 69., 70., 72., 74., 75., 76.]])

In [14]:
y_test = np.array([2, 7, 11]).reshape(3, 1)
y_test

array([[ 2],
       [ 7],
       [11]])

In [15]:
y_pred = model_rnn.predict(X_test)

1/1 [==============================] - 0s 266ms/step


In [16]:
y_pred

array([[ 2.2630389],
       [ 7.3277082],
       [11.290433 ]], dtype=float32)

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [18]:
f = open("/content/drive/MyDrive/datasets/dostoevsky.txt", 'r')
data_for_word_predictions = f.read()
len(data_for_word_predictions)

11321999

In [19]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize, sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [20]:
from nltk.tokenize import WordPunctTokenizer
tokenizer = WordPunctTokenizer()

In [21]:
words = word_tokenize(data_for_word_predictions)

In [22]:
print(len([word for word in words if word.lower() == 'бесы'])/len(words) * 100, '%')
print(len([word for word in words if word.lower() == 'семья'])/len(words) * 100, '%')
print(len([word for word in words if word.lower() == 'брат'])/len(words) * 100, '%')

0.0006506223202493185 %
0.0009542460696990004 %
0.02394290138517492 %


In [23]:
import string
punktuation = string.punctuation
punktuation+='«'+'»'+'—'

In [24]:
def clean_punktuacy(x):
    return [word for word in x if not word in punktuation]

In [25]:
words = clean_punktuacy(words)

In [26]:
len(words)

1811440

In [27]:
words

['\ufeffФедор',
 'Михайлович',
 'Достоевский',
 'Бедные',
 'люди',
 'Ох',
 'уж',
 'эти',
 'мне',
 'сказочники',
 'Нет',
 'чтобы',
 'написать',
 'что-нибудь',
 'полезное',
 'приятное',
 'усладительное',
 'а',
 'то',
 'всю',
 'подноготную',
 'в',
 'земле',
 'вырывают',
 '..',
 'Вот',
 'уж',
 'запретил',
 'бы',
 'им',
 'писать',
 'Ну',
 'на',
 'что',
 'это',
 'похоже',
 'читаешь…',
 'невольно',
 'задумываешься',
 'а',
 'там',
 'всякая',
 'дребедень',
 'и',
 'пойдет',
 'в',
 'голову',
 'право',
 'бы',
 'запретил',
 'им',
 'писать',
 'так-таки',
 'просто',
 'вовсе',
 'бы',
 'запретил',
 'Кн',
 'В.',
 'Ф.',
 'Одоевский',
 'Апреля',
 '8-го',
 'Бесценная',
 'моя',
 'Варвара',
 'Алексеевна',
 'Вчера',
 'я',
 'был',
 'счастлив',
 'чрезмерно',
 'счастлив',
 'донельзя',
 'счастлив',
 'Вы',
 'хоть',
 'раз',
 'в',
 'жизни',
 'упрямица',
 'меня',
 'послушались',
 'Вечером',
 'часов',
 'в',
 'восемь',
 'просыпаюсь',
 'вы',
 'знаете',
 'маточка',
 'что',
 'я',
 'часочек-другой',
 'люблю',
 'поспать',
 

In [28]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [29]:
stopWords = set(stopwords.words('russian'))
print(stopWords)

{'все', 'уж', 'быть', 'мы', 'где', 'я', 'в', 'ей', 'кто', 'то', 'перед', 'до', 'разве', 'ну', 'они', 'под', 'будто', 'нее', 'конечно', 'но', 'теперь', 'много', 'меня', 'для', 'не', 'этой', 'потому', 'такой', 'никогда', 'когда', 'другой', 'было', 'можно', 'ж', 'он', 'тут', 'надо', 'нельзя', 'почти', 'тогда', 'всегда', 'без', 'ничего', 'больше', 'или', 'тебя', 'их', 'у', 'а', 'три', 'от', 'него', 'со', 'что', 'них', 'этот', 'нет', 'всех', 'чего', 'нас', 'один', 'эти', 'хоть', 'себе', 'был', 'тем', 'вот', 'только', 'если', 'даже', 'того', 'чуть', 'ней', 'мой', 'ним', 'нибудь', 'сам', 'так', 'были', 'ты', 'всю', 'к', 'им', 'лучше', 'впрочем', 'хорошо', 'его', 'сейчас', 'через', 'ему', 'ли', 'она', 'может', 'ни', 'чтобы', 'из', 'том', 'этого', 'два', 'как', 'моя', 'тот', 'тоже', 'мне', 'про', 'куда', 'об', 'себя', 'при', 'по', 'и', 'эту', 'наконец', 'вас', 'же', 'свою', 'какая', 'во', 'вы', 'вдруг', 'какой', 'на', 'ее', 'раз', 'здесь', 'потом', 'этом', 'за', 'еще', 'о', 'чем', 'будет', 'ино

In [30]:
words = [word for word in words if word.lower() not in stopWords]

In [31]:
words

['\ufeffФедор',
 'Михайлович',
 'Достоевский',
 'Бедные',
 'люди',
 'Ох',
 'сказочники',
 'написать',
 'что-нибудь',
 'полезное',
 'приятное',
 'усладительное',
 'подноготную',
 'земле',
 'вырывают',
 '..',
 'запретил',
 'писать',
 'это',
 'похоже',
 'читаешь…',
 'невольно',
 'задумываешься',
 'всякая',
 'дребедень',
 'пойдет',
 'голову',
 'право',
 'запретил',
 'писать',
 'так-таки',
 'просто',
 'вовсе',
 'запретил',
 'Кн',
 'В.',
 'Ф.',
 'Одоевский',
 'Апреля',
 '8-го',
 'Бесценная',
 'Варвара',
 'Алексеевна',
 'Вчера',
 'счастлив',
 'чрезмерно',
 'счастлив',
 'донельзя',
 'счастлив',
 'жизни',
 'упрямица',
 'послушались',
 'Вечером',
 'часов',
 'восемь',
 'просыпаюсь',
 'знаете',
 'маточка',
 'часочек-другой',
 'люблю',
 'поспать',
 'должности',
 'свечку',
 'достал',
 'приготовляю',
 'бумаги',
 'чиню',
 'перо',
 'невзначай',
 'подымаю',
 'глаза',
 'право',
 'сердце',
 'запрыгало',
 'вы-таки',
 'поняли',
 'хотелось',
 'сердчишку',
 'моему',
 'хотелось',
 'Вижу',
 'уголочек',
 'занаве

In [32]:
len(sent_tokenize(data_for_word_predictions))

123550

In [33]:
import gensim.downloader as api
model_embedding = api.load('glove-twitter-100')

[==================================================] 100.0% 387.1/387.1MB downloaded


In [34]:
list_of_words = []
list_of_words_answer = []
for i in range(500):
    list_of_words.append(words[i:i+10])
    list_of_words_answer.append(words[i+11])



In [35]:
list_of_words[0], list_of_words_answer[0]

(['\ufeffФедор',
  'Михайлович',
  'Достоевский',
  'Бедные',
  'люди',
  'Ох',
  'сказочники',
  'написать',
  'что-нибудь',
  'полезное'],
 'усладительное')

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(list_of_words, list_of_words_answer, test_size=0.2, random_state=42)

In [38]:
for sequence in range(len(list_of_words)):
    for word in range(len(list_of_words[sequence])):
        try:
            list_of_words[sequence][word] = model_embedding[list_of_words[sequence][word].lower()]
        except:
            list_of_words[sequence][word] = model_embedding['слово']


In [39]:
np.array(list_of_words)

array([[[-0.35316 , -0.71943 , -0.35336 , ..., -1.2644  ,  1.4338  ,
          0.15721 ],
        [ 0.34474 ,  0.27934 , -0.55781 , ..., -0.39853 ,  0.18373 ,
          0.21332 ],
        [ 0.045464,  0.44602 , -0.059784, ..., -0.81965 ,  0.29428 ,
         -0.046842],
        ...,
        [ 0.9066  ,  0.19817 , -0.13572 , ..., -1.4654  ,  0.75209 ,
         -0.51616 ],
        [-0.11144 ,  0.069021, -0.12677 , ..., -1.2221  ,  0.38973 ,
         -0.45124 ],
        [-0.1702  , -0.53173 , -0.72272 , ..., -0.035506,  0.99899 ,
         -0.1479  ]],

       [[ 0.34474 ,  0.27934 , -0.55781 , ..., -0.39853 ,  0.18373 ,
          0.21332 ],
        [ 0.045464,  0.44602 , -0.059784, ..., -0.81965 ,  0.29428 ,
         -0.046842],
        [ 0.3366  , -0.36821 , -0.19048 , ..., -1.0845  ,  0.11068 ,
          0.37869 ],
        ...,
        [-0.11144 ,  0.069021, -0.12677 , ..., -1.2221  ,  0.38973 ,
         -0.45124 ],
        [-0.1702  , -0.53173 , -0.72272 , ..., -0.035506,  0.99899 ,
   

In [40]:
list_of_words = np.array(list_of_words).round(2)

In [41]:
for word in range(len(list_of_words_answer)):
        try:
            list_of_words_answer[word] = model_embedding[list_of_words_answer[word]]
        except:
            list_of_words_answer[word] = model_embedding['и']

In [42]:
np.array(list_of_words_answer)

array([[ 0.11342 ,  0.08166 , -0.82316 , ..., -1.3245  , -0.086748,
        -0.63775 ],
       [ 0.11342 ,  0.08166 , -0.82316 , ..., -1.3245  , -0.086748,
        -0.63775 ],
       [-0.1012  ,  0.44361 , -0.29656 , ..., -0.84949 , -0.4401  ,
        -0.25279 ],
       ...,
       [ 0.364   ,  0.037661, -0.33153 , ..., -0.75432 ,  1.2062  ,
         0.028971],
       [ 0.20694 ,  0.32604 , -0.26658 , ..., -1.3265  ,  2.0129  ,
         0.045418],
       [ 0.11342 ,  0.08166 , -0.82316 , ..., -1.3245  , -0.086748,
        -0.63775 ]], dtype=float32)

In [43]:
list_of_words_answer = np.array(list_of_words_answer).round(2)

In [44]:
X_train, X_test, y_train, y_test = train_test_split(list_of_words, list_of_words_answer, test_size=0.2, random_state=42)

In [45]:
X_train

array([[[-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [ 0.46,  0.02, -0.57, ..., -2.23,  1.34, -0.11],
        ...,
        [-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [-0.58,  0.03, -0.79, ..., -0.24, -0.7 , -0.3 ]],

       [[-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [ 0.49,  0.28, -0.51, ..., -1.31, -0.24, -0.15],
        [ 0.22, -0.2 , -0.11, ..., -0.2 , -0.79,  0.64],
        ...,
        [-0.15, -0.17, -0.63, ..., -1.97, -0.64, -0.41],
        [-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [-0.83, -0.26, -0.74, ..., -0.11, -0.84, -0.31]],

       [[ 0.18, -0.1 , -0.17, ..., -1.11,  0.51, -0.01],
        [-0.35, -0.72, -0.35, ..., -1.26,  1.43,  0.16],
        [ 0.48,  0.06,  0.09, ..., -0.08, -0.83,  0.05],
        ...,
        [-0.03,  0.18,  0.79, ..., -1.32, -0.7 , -0.08],
        [ 0.23,  0.55,  0.1 , ..., -1.18,  1.

In [46]:
model_rnn = keras.Sequential()



model_rnn.add(LSTM(1024, activation='tanh', return_sequences=True))
model_rnn.add(LSTM(1024, activation='tanh', return_sequences=False))
model_rnn.add(Dense(1024, activation='tanh'))
model_rnn.add(Dense(1024, activation='tanh'))
model_rnn.add(Dense(1024, activation='tanh'))
model_rnn.add(Dense(100, activation='tanh'))

model_rnn.compile(loss='mse', optimizer=keras.optimizers.Adam(0.001))

In [47]:
model_rnn.fit(X_train, y_train, epochs=100)

Epoch 1/100
13/13 [==============================] - 8s 26ms/step - loss: 0.3920
Epoch 2/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2531
Epoch 3/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2384
Epoch 4/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2322
Epoch 5/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2270
Epoch 6/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2228
Epoch 7/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2206
Epoch 8/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2178
Epoch 9/100
13/13 [==============================] - 0s 19ms/step - loss: 0.2137
Epoch 10/100
13/13 [==============================] - 0s 18ms/step - loss: 0.2058
Epoch 11/100
13/13 [==============================] - 0s 17ms/step - loss: 0.2014
Epoch 12/100
13/13 [==============================] - 0s 18ms/step - loss: 0.1949
Epoch 13/100
13/13 [=====

In [48]:
def text_generate(text):
    vectors = []
    vectors.append(text.lower().split())
    for i in range(len(vectors[0])):
        try:
            vectors[0][i] = model_embedding[vectors[0][i]]
        except:
            vectors[0][i] = model_embedding['и']
    return np.array(vectors)



In [49]:
text = text_generate('Я люблю котов и собак и даже возможно произведения федора')

In [50]:
word_pred = model_rnn.predict(text)

1/1 [==============================] - 1s 924ms/step


In [51]:
word_pred

array([[ 0.03510349, -0.03351927, -0.7137872 , -0.24312891, -0.8206559 ,
         0.61096317, -0.31605023, -0.36187413,  0.3078959 ,  0.52098554,
         0.99244756,  0.36941186,  0.12673527, -0.1403597 ,  0.311479  ,
        -0.41313565,  0.3553056 ,  0.48729584,  0.70337576,  0.5098838 ,
         0.6147807 ,  0.5124636 ,  0.35554662,  0.96144706,  0.233886  ,
         0.13345286, -0.17060456,  0.29529095,  0.98223805, -0.61238784,
         0.02485115, -0.9601224 , -0.37023488,  0.99003404,  0.00755851,
        -0.02206224,  0.30215743, -0.5249067 , -0.15103169, -0.43224725,
         0.7728624 ,  0.8357374 , -0.948301  ,  0.0407276 ,  0.0350786 ,
        -0.00740452,  0.88642377,  0.07530824, -0.97604936, -0.07027877,
         0.08235906, -0.26260245,  0.2249323 , -0.74242735,  0.70660627,
         0.17891707,  0.36976328, -0.22151275, -0.9177471 ,  0.24416405,
         0.1604539 , -0.97304326,  0.09452332, -0.5240254 , -0.9935614 ,
        -0.38873956, -0.3772676 , -0.12689184,  0.3

In [52]:
model_embedding.similar_by_vector(word_pred[0])

[('и', 0.9631007313728333),
 ('а', 0.7645843029022217),
 ('но', 0.7501345872879028),
 ('или', 0.7467753291130066),
 ('то', 0.7313318848609924),
 ('я', 0.7298493981361389),
 ('вот', 0.7256402969360352),
 ('тоже', 0.7229993939399719),
 ('с', 0.7207965850830078),
 ('потом', 0.719173014163971)]

In [53]:
from random import randint

In [54]:
def words_predict(text, number_of_words):
    text_for_work = text.split()
    for i in range(number_of_words):
        text = text_generate(" ".join(text_for_work[-10:]))
        text_for_work.append(model_embedding.similar_by_vector(model_rnn.predict(text)[0])[randint(0, 5)][0])
    return " ".join(text_for_work)

In [55]:
words_predict('в начале июля в чрезвычайно жаркое время под вечер один', 10)

1/1 [==============================] - 0s 29ms/step


'в начале июля в чрезвычайно жаркое время под вечер один но однако так и все сразу сейчас сегодня а с'